apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2020-08-26T08:14:45Z"
    labels:
      app: quotesapi
    name: quotesapi
    namespace: stan-shih-quotes-dev
    resourceVersion: "124355966"
    selfLink: /apis/build.openshift.io/v1/namespaces/stan-shih-quotes-dev/buildconfigs/quotesapi
    uid: 33a8c44c-e774-11ea-87eb-0a580a800041
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: quotesapi:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: quotes
      git:
        uri: https://github.com/loverain97620/DO288-apps
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: b1f7IwymjBwdrYHh2a20
      type: GitHub
    - generic:
        secret: Wb4_7BF22Z3KjtrGrCsB
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/php@sha256:a5aaaae5baf98cb674ac2352429e0450591b45d3674e44c516612a9ee67282d5
      type: ImageChange
  status:
    lastVersion: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
