apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
      volume.kubernetes.io/selected-node: ip-10-0-143-194.ec2.internal
    creationTimestamp: "2020-08-26T08:13:53Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: quotesdb-claim
    namespace: stan-shih-quotes-dev
    resourceVersion: "124355621"
    selfLink: /api/v1/namespaces/stan-shih-quotes-dev/persistentvolumeclaims/quotesdb-claim
    uid: 148125e7-e774-11ea-8f8f-02e5d704b7db
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 300Mi
    storageClassName: gp2
    volumeMode: Filesystem
    volumeName: pvc-148125e7-e774-11ea-8f8f-02e5d704b7db
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
